apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: database-proxy-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: database-proxy-app
  endpoints:
  - port: http-web
    path: /prometheus
  targetLabels:
    - application
