apiVersion: v1
kind: Service
metadata:
  name: database-proxy-svc
  labels:
    app: database-proxy-app
    application: database-proxy
spec:
  selector:
    app: database-proxy-app
  ports:
    - protocol: TCP
      port: 32003
      targetPort: 8080
      name: http-web
  type: LoadBalancer
