apiVersion: v1
kind: Service
metadata:
  name: grafana-expose
  labels:
    app: grafana-expose
spec:
  ports:
  - name: http-web
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  type: LoadBalancer
status:
  loadBalancer: {}
  