apiVersion: v1
kind: Service
metadata:
  name: prometheus-expose
  labels:
    app: prometheus-expose
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 31090
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
  type: NodePort
status:
  loadBalancer: {}
  