apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.6.1
        ports:
        - containerPort: 9092
        - containerPort: 9101
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_JMX_HOSTNAME
          value: "localhost"
        - name: KAFKA_PROCESS_ROLES
          value: 'broker,controller'
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: '1@broker:29093'
        - name: KAFKA_LISTENERS
          value: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'PLAINTEXT'
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: 'CONTROLLER'
        - name: KAFKA_LOG_DIRS
          value: '/tmp/kraft-combined-logs'
        - name: CLUSTER_ID
          value: 'MkU3OEVBNTcwNTJENDM2Qk'
