
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    name: default
  - protocol: TCP
    port: 9101
    targetPort: 9101
    name: jmx
