apiVersion: v1
kind: Service
metadata:
  name: load-tests-svc
  labels:
    app: load-tests-app
    application: load-tests
spec:
  selector:
    app: load-tests-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      name: http-web
  type: LoadBalancer