apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: source-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: source-exporter-app
  endpoints:
  - port: http
