apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: replica-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: replica-exporter-app
  endpoints:
  - port: http
