apiVersion: v1
kind: Service
metadata:
  name: source-exporter-svc
  labels:
    app: source-exporter-app
spec:
  type: ClusterIP
  ports:
  - port: 9104
    protocol: TCP
    name: http
  selector:
    app: source-exporter-app