apiVersion: v1
kind: Service
metadata:
  name: order-management-svc
  labels:
    app: order-management-app
    application: order-management
spec:
  selector:
    app: order-management-app
  ports:
    - protocol: TCP
      port: 32001
      nodePort: 32001
      targetPort: 8080
      name: http-web
  type: NodePort