apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader-app
  template:
    metadata:
      labels:
        app: reader-app
    spec:
      containers:
        - name: reader-container
          image: us-central1-docker.pkg.dev/thesis-416800/uoc/reader:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred