apiVersion: v1
kind: Service
metadata:
  name: reader-svc
  labels:
    app: reader-app
    application: reader
spec:
  selector:
    app: reader-app
  ports:
    - protocol: TCP
      port: 30080
      nodePort: 30080
      targetPort: 8080
      name: http-web
  type: NodePort