apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-status-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: order-status-app
  endpoints:
  - port: http-web
    path: /prometheus
  targetLabels:
    - application
