apiVersion: v1
kind: Service
metadata:
  name: order-status-svc
  labels:
    app: order-status-app
    application: order-status
spec:
  selector:
    app: order-status-app
  ports:
    - protocol: TCP
      port: 32002
      targetPort: 8080
      name: http-web
  type: LoadBalancer